### PR TITLE
Draft version 1.0.9 with errata integrated.

### LINKED ISSUE #25: SDE if in-scope delimiter value clashes with an escapeCharacter or escapeEscapeCharacter value
(was Action 323)
Spec is not clear this is an error. 

Verified that IBM DFDL throws SDE.

### PR DESCRIPTION
**Pull request by mbeckerle**
Fixes #25, #26, #28, #29, #31, #38, #39, #42

### CODE REVIEW

**Comment by mbeckerle** [comment]
Currently I have change bars on in the text at the site of the changes. 

Do we want just margin change bars, without the underlining/color stuff for the changes? (I'm unsure how to do that, but maybe worth trying)

**Comment by mbeckerle** [comment]
See https://github.com/OpenGridForum/DFDL/issues/29#issuecomment-1563063273

**Review by smhdfdl — CHANGES_REQUESTED** [review]
I think it looks good.

One change to the errata would be beneficial:

Page 186, the new note 6 to Table 55. I mis-parsed the sentence, so I think it's clearer as "The expression ".[1]" is the same as ".". The expression ".[n]" where n is not equal to 1 returns an empty node sequence."

I also think technically ".[1]" and ".[n]" are not "expressions" but are "_FilterExpr_" . So I prefer "The _FilterExpr_ ".[1]" is the same as ".". The _FilterExpr_ ".[n]" where n is not equal to 1 returns an empty node sequence."

Also spotted that
- Your 2nd email address on p203 is not a hyperlink
- My email address needs changing to smhdfdl@gmail.com
- Maybe my address should just be "IBM UK (retired)" with no Hursley etc
- Could add "IBM UK (retired)" for Alan too?

Of course that got me looking at the list of other contributors. 
- Tim Kimber is now at Prolifics, UK
- Stephanie Fetzer is now at HCL, USA
- Geoff Judd & Peter Lambros are both "IBM UK (retired)"

**Comment by mbeckerle** [comment]
All items per @smhdfdl comment above have been made. There are 3 contributors where I couldn't find them on linked-in to update their affiliations. (Tara Gibson, Steve Marting, Alejandro Rodriguez)

I did not do track-changes on the affiliation updates. 

The #29 change to prohibit assert, discriminator, and setVariable from prefix length types was also made, and the change log updated to reflect that additional change to prefixLengthType.

**Review by smhdfdl — APPROVED** [review]
Looks good

**Pull request merged**
